export interface MrCryptoMetadataType {
  name: string;
  description: Description;
  image: string;
  dna: string;
  edition: number;
  date: number;
  attributes: Attribute[];
}

export interface Attribute {
  trait_type: TraitType;
  value: Value;
}

export enum TraitType {
  Background = "Background",
  Clothes = "Clothes",
  Eyes = "Eyes",
  Headwear = "Headwear",
  Moustache = "Moustache",
  Type = "Type",
}

export enum Value {
  ATM = "ATM",
  Alien = "Alien",
  Anime = "Anime",
  Army = "Army",
  BTCBlackCap = "BTC Black Cap",
  BTCBowTie = "BTC Bow Tie",
  BTCHat = "BTC Hat",
  BTCRedCap = "BTC Red Cap",
  BTCWhiteCap = "BTC White Cap",
  Bad = "Bad",
  BadBlue = "Bad Blue",
  BadYellow = "Bad Yellow",
  Bald = "Bald",
  BeardTonge = "Beard Tonge",
  BitBaseHat = "BitBase Hat",
  Black = "Black ",
  BlackBTCBowTie = "Black BTC Bow Tie",
  BlackMoustache = "Black Moustache",
  BlondeHair = "Blonde Hair",
  BlondeStyledHair = "Blonde Styled Hair",
  Blue = "Blue",
  BlueBowTie = "Blue Bow Tie",
  BlueHat = "Blue Hat",
  BlueHoodie = "Blue Hoodie",
  Brown = "Brown",
  Btc = "BTC",
  Cat = "Cat",
  CianBowTie = "Cian Bow Tie",
  CianHat = "Cian Hat",
  Cigar = "Cigar",
  CigarSimple = "Cigar Simple",
  Classic = "Classic",
  ClassicBowTie = "Classic Bow Tie",
  ClassicHat = "Classic Hat",
  CreamCardigan = "Cream Cardigan",
  DarkBlue = "Dark Blue",
  DarkGray = "Dark Gray",
  Dead = "Dead",
  DeepBlueBowTie = "Deep Blue Bow Tie",
  DeepBlueHat = "Deep Blue Hat",
  DeepBlueSimple = "Deep Blue Simple",
  DemonHorns = "Demon Horns",
  Depilated = "Depilated",
  Dreadlocks = "Dreadlocks",
  Fuchsia = "Fuchsia",
  GradientHaircut = "Gradient Haircut",
  Gray = "Gray",
  GreenBowTie = "Green Bow Tie",
  GreenHat = "Green Hat",
  GreenMoney = "Green Money",
  GreyBTC = "Grey BTC",
  GreyBowTie = "Grey Bow Tie",
  HelicopterHat = "Helicopter Hat",
  Hollow = "Hollow",
  HollowBTC = "Hollow BTC",
  HollowLaser = "Hollow Laser",
  Hoodie = "Hoodie",
  Human = "Human",
  JesusCrypt = "Jesus Crypt",
  Kawaii = "Kawaii",
  Laser = "Laser",
  Lime = "Lime",
  LineHaircut = "Line Haircut",
  LongBlondeHair = "Long Blonde Hair",
  LongDarkHair = "Long Dark Hair",
  Martian = "Martian",
  McHodlerBlackCap = "McHodler Black Cap",
  McHodlerRedCap = "McHodler Red Cap",
  Mint = "Mint",
  MintHat = "Mint Hat",
  MintTonge = "Mint Tonge",
  MoneyGreen = "Money Green",
  Monkey = "Monkey",
  MrSkull = "Mr. Skull",
  MyProCap = "MyPro Cap",
  MyProShirt = "MyPro Shirt",
  Nsujpg = "NSUJPG",
  OffShoreHoodie = "Off-Shore Hoodie",
  Orange = "Orange",
  OrangeBeanie = "Orange Beanie",
  OrangeBowTie = "Orange Bow Tie",
  OrangeHat = "Orange Hat",
  Panda = "Panda",
  Party = "Party",
  Pink = "Pink",
  PinkBowTie = "Pink Bow Tie",
  PinkCardigan = "Pink Cardigan",
  PinkHat = "Pink Hat",
  PinkNYellowBowTie = "Pink n Yellow Bow Tie",
  PinkNYellowHat = "Pink n Yellow Hat",
  Pumpkin = "Pumpkin",
  Purple = "Purple",
  PurpleBeanie = "Purple Beanie",
  RacksShirt = "Racks Shirt",
  RedBTC = "Red BTC",
  RedBeanie = "Red Beanie",
  RedHat = "Red Hat",
  RukaShirt = "Ruka Shirt",
  SimpleCigar = "Simple Cigar",
  SkullMouth = "Skull Mouth",
  Small = "Small",
  Smile = "Smile",
  SmileCigar = "Smile Cigar",
  SpacesuitBlack = "Spacesuit Black",
  SpacesuitWhite = "Spacesuit White",
  SpainBTCBowTie = "Spain BTC Bow Tie",
  SpainHat = "Spain Hat",
  Spruce = "Spruce",
  SpruceHat = "Spruce Hat",
  SteelBlue = "Steel Blue",
  StyledBrownHair = "Styled Brown Hair",
  Tonge = "Tonge",
  TrumpHair = "Trump Hair",
  VivaRacksMafia = "Viva Racks Mafia",
  VividGreenHat = "Vivid Green Hat",
  VividYellow = "Vivid Yellow",
  WallStreet = "Wall Street",
  WhiteBowTie = "White Bow Tie",
  WhiteHair = "White Hair",
  WhiteHat = "White Hat",
  WhiteMoustache = "White Moustache",
  WillyBeret = "Willy Beret",
  XmasBeanie = "Xmas Beanie",
  Yellow = "Yellow",
  Zombie = "Zombie",
}

export enum Description {
  TheOfficialRACKSNFTCollection = "The official RACKS® NFT collection",
}
